blank_issues_enabled: true
contact_links:
  - name: Community Slack
    url: https://cloud-native.slack.com/archives/CJ1KHJM5Z
    about: Chat with the community about any issues, questions, or feedback