name: Report a bug
description: A clear and concise description of what the bug is.
title: "[Bug Report]:"
labels:
  - bug-report
body:
  - type: markdown
    attributes:
      value: |

        * For questions, ask in [Slack](https://cloud-native.slack.com/archives/CJ1KHJM5Z).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/oras-project/oras-www/issues).

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: |
        - Give as much detail as you can to help us understand the bug you want to report.
        - Go to '...'
        - Click on '...'
        - Scroll down to '...'
        - See the error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or screen captures to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context?
      description: Any additional information, configuration, or data that might be necessary to reproduce the issue.
    validations:
      required: false